{
  .start = (void *)&_binary_model_tavion_new_legs_vq_start,
  .size = (uint32_t)&_binary_model_tavion_new_legs_vq_size,
  .offset = 0,
  .width = 512,
  .height = 512,
  .v_mul = 1.0, // 512
},
{
  .start = (void *)&_binary_model_tavion_new_torso_vq_start,
  .size = (uint32_t)&_binary_model_tavion_new_torso_vq_size,
  .offset = 67648,
  .width = 512,
  .height = 512,
  .v_mul = 1.0, // 512
},
{
  .start = (void *)&_binary_model_tavion_new_head_vq_start,
  .size = (uint32_t)&_binary_model_tavion_new_head_vq_size,
  .offset = 135296,
  .width = 512,
  .height = 512,
  .v_mul = 1.0, // 512
},
{
  .start = (void *)&_binary_model_tavion_new_face_vq_start,
  .size = (uint32_t)&_binary_model_tavion_new_face_vq_size,
  .offset = 202944,
  .width = 512,
  .height = 512,
  .v_mul = 1.0, // 512
},
{
  .start = (void *)&_binary_model_tavion_new_arm_vq_start,
  .size = (uint32_t)&_binary_model_tavion_new_arm_vq_size,
  .offset = 270592,
  .width = 512,
  .height = 512,
  .v_mul = 1.0, // 512
},
{
  .start = (void *)&_binary_model_tavion_new_hands_vq_start,
  .size = (uint32_t)&_binary_model_tavion_new_hands_vq_size,
  .offset = 338240,
  .width = 256,
  .height = 128,
  .v_mul = 1.0, // 128
},
