#define CCR__IIX (1 << 15)
#define CCR__ICI (1 << 11)
#define CCR__ICE (1 << 8)
#define CCR__OIX (1 << 7)
#define CCR__ORA (1 << 5)
#define CCR__OCI (1 << 4)
#define CCR__CB  (1 << 2)
#define CCR__WT  (1 << 1)
#define CCR__OCE (1 << 0)

#define PDTRA__MASK     (0b11 << 8)
#define PDTRA__VGA      (0b00 << 8)
#define PDTRA__RESERVED (0b01 << 8)
#define PDTRA__RGB      (0b10 << 8)
#define PDTRA__AV       (0b11 << 8)
