#pragma once
#include <cstdint>
extern uint32_t _binary_model_sheik_sheik_00_alpha_pal_start __asm("_binary_model_sheik_sheik_00_alpha_pal_start");
extern uint32_t _binary_model_sheik_sheik_00_alpha_pal_end __asm("_binary_model_sheik_sheik_00_alpha_pal_end");
extern uint32_t _binary_model_sheik_sheik_00_alpha_pal_size __asm("_binary_model_sheik_sheik_00_alpha_pal_size");
