{
  .start = (void *)0,
  .size = (uint32_t)0,
  .offset = 0,
  .width = 0,
  .height = 0,
  .v_mul = 0, // 0
},
{
  .start = (void *)&_binary_bsp_20kdm2_textures_e7_e7walldesign01b_data_start,
  .size = (uint32_t)&_binary_bsp_20kdm2_textures_e7_e7walldesign01b_data_size,
  .offset = 0,
  .width = 256,
  .height = 1024,
  .v_mul = 0.625, // 640
},
{
  .start = (void *)&_binary_bsp_20kdm2_textures_e7_e7steptop2_data_start,
  .size = (uint32_t)&_binary_bsp_20kdm2_textures_e7_e7steptop2_data_size,
  .offset = 163840,
  .width = 256,
  .height = 32,
  .v_mul = 1.0, // 32
},
{
  .start = (void *)0,
  .size = (uint32_t)0,
  .offset = 172032,
  .width = 0,
  .height = 0,
  .v_mul = 0, // 0
},
{
  .start = (void *)&_binary_bsp_20kdm2_textures_e7_e7dimfloor_data_start,
  .size = (uint32_t)&_binary_bsp_20kdm2_textures_e7_e7dimfloor_data_size,
  .offset = 172032,
  .width = 128,
  .height = 128,
  .v_mul = 1.0, // 128
},
{
  .start = (void *)&_binary_bsp_20kdm2_textures_e7_e7brickfloor01_data_start,
  .size = (uint32_t)&_binary_bsp_20kdm2_textures_e7_e7brickfloor01_data_size,
  .offset = 188416,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)&_binary_bsp_20kdm2_textures_e7_e7bmtrim_data_start,
  .size = (uint32_t)&_binary_bsp_20kdm2_textures_e7_e7bmtrim_data_size,
  .offset = 253952,
  .width = 256,
  .height = 64,
  .v_mul = 1.0, // 64
},
{
  .start = (void *)&_binary_bsp_20kdm2_textures_e7_e7sbrickfloor_data_start,
  .size = (uint32_t)&_binary_bsp_20kdm2_textures_e7_e7sbrickfloor_data_size,
  .offset = 270336,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)&_binary_bsp_20kdm2_textures_e7_e7brnmetal_data_start,
  .size = (uint32_t)&_binary_bsp_20kdm2_textures_e7_e7brnmetal_data_size,
  .offset = 335872,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)0,
  .size = (uint32_t)0,
  .offset = 401408,
  .width = 0,
  .height = 0,
  .v_mul = 0, // 0
},
{
  .start = (void *)&_binary_bsp_20kdm2_textures_e7_e7beam02_red_data_start,
  .size = (uint32_t)&_binary_bsp_20kdm2_textures_e7_e7beam02_red_data_size,
  .offset = 401408,
  .width = 64,
  .height = 128,
  .v_mul = 1.0, // 128
},
{
  .start = (void *)&_binary_bsp_20kdm2_textures_e7_e7swindow_data_start,
  .size = (uint32_t)&_binary_bsp_20kdm2_textures_e7_e7swindow_data_size,
  .offset = 409600,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)&_binary_bsp_20kdm2_textures_e7_e7bigwall_data_start,
  .size = (uint32_t)&_binary_bsp_20kdm2_textures_e7_e7bigwall_data_size,
  .offset = 475136,
  .width = 256,
  .height = 1024,
  .v_mul = 0.75, // 768
},
{
  .start = (void *)&_binary_bsp_20kdm2_textures_e7_e7panelwood_data_start,
  .size = (uint32_t)&_binary_bsp_20kdm2_textures_e7_e7panelwood_data_size,
  .offset = 671744,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)&_binary_bsp_20kdm2_textures_e7_e7beam01_data_start,
  .size = (uint32_t)&_binary_bsp_20kdm2_textures_e7_e7beam01_data_size,
  .offset = 737280,
  .width = 64,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)&_binary_bsp_20kdm2_textures_gothic_floor_xstepborder5_data_start,
  .size = (uint32_t)&_binary_bsp_20kdm2_textures_gothic_floor_xstepborder5_data_size,
  .offset = 753664,
  .width = 256,
  .height = 64,
  .v_mul = 0.78125, // 50
},
{
  .start = (void *)&_binary_bsp_20kdm2_textures_liquids_lavahell_data_start,
  .size = (uint32_t)&_binary_bsp_20kdm2_textures_liquids_lavahell_data_size,
  .offset = 766464,
  .width = 128,
  .height = 128,
  .v_mul = 1.0, // 128
},
{
  .start = (void *)&_binary_bsp_20kdm2_textures_e7_e7steptop_data_start,
  .size = (uint32_t)&_binary_bsp_20kdm2_textures_e7_e7steptop_data_size,
  .offset = 782848,
  .width = 256,
  .height = 32,
  .v_mul = 1.0, // 32
},
{
  .start = (void *)&_binary_bsp_20kdm2_textures_gothic_trim_metalblackwave01_data_start,
  .size = (uint32_t)&_binary_bsp_20kdm2_textures_gothic_trim_metalblackwave01_data_size,
  .offset = 791040,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)&_binary_bsp_20kdm2_textures_stone_pjrock1_data_start,
  .size = (uint32_t)&_binary_bsp_20kdm2_textures_stone_pjrock1_data_size,
  .offset = 856576,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)0,
  .size = (uint32_t)0,
  .offset = 922112,
  .width = 0,
  .height = 0,
  .v_mul = 0, // 0
},
{
  .start = (void *)0,
  .size = (uint32_t)0,
  .offset = 922112,
  .width = 0,
  .height = 0,
  .v_mul = 0, // 0
},
{
  .start = (void *)&_binary_bsp_20kdm2_models_mapobjects_timlamp_timlamp_data_start,
  .size = (uint32_t)&_binary_bsp_20kdm2_models_mapobjects_timlamp_timlamp_data_size,
  .offset = 922112,
  .width = 128,
  .height = 128,
  .v_mul = 1.0, // 128
},
{
  .start = (void *)0,
  .size = (uint32_t)0,
  .offset = 938496,
  .width = 0,
  .height = 0,
  .v_mul = 0, // 0
},
{
  .start = (void *)&_binary_bsp_20kdm2_textures_sfx_flame2_data_start,
  .size = (uint32_t)&_binary_bsp_20kdm2_textures_sfx_flame2_data_size,
  .offset = 938496,
  .width = 128,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)&_binary_bsp_20kdm2_models_mapobjects_gratelamp_gratetorch2_data_start,
  .size = (uint32_t)&_binary_bsp_20kdm2_models_mapobjects_gratelamp_gratetorch2_data_size,
  .offset = 971264,
  .width = 32,
  .height = 64,
  .v_mul = 1.0, // 64
},
{
  .start = (void *)&_binary_bsp_20kdm2_models_mapobjects_gratelamp_gratetorch2b_data_start,
  .size = (uint32_t)&_binary_bsp_20kdm2_models_mapobjects_gratelamp_gratetorch2b_data_size,
  .offset = 973312,
  .width = 32,
  .height = 64,
  .v_mul = 1.0, // 64
},
