#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

extern uint32_t _binary_bsp_katdm3_textures_katdm3_kattex_3_stone_bmp_rot_data_start __asm("_binary_bsp_katdm3_textures_katdm3_kattex_3_stone_bmp_rot_data_start");
extern uint32_t _binary_bsp_katdm3_textures_katdm3_kattex_3_stone_bmp_rot_data_end __asm("_binary_bsp_katdm3_textures_katdm3_kattex_3_stone_bmp_rot_data_end");
extern uint32_t _binary_bsp_katdm3_textures_katdm3_kattex_3_stone_bmp_rot_data_size __asm("_binary_bsp_katdm3_textures_katdm3_kattex_3_stone_bmp_rot_data_size");

#ifdef __cplusplus
}
#endif
