#pragma once
#include <cstdint>
extern uint32_t _binary_texture_panda_panda_rectangular_vq_start __asm("_binary_texture_panda_panda_rectangular_vq_start");
extern uint32_t _binary_texture_panda_panda_rectangular_vq_end __asm("_binary_texture_panda_panda_rectangular_vq_end");
extern uint32_t _binary_texture_panda_panda_rectangular_vq_size __asm("_binary_texture_panda_panda_rectangular_vq_size");
