#pragma once
#include <cstdint>
extern uint32_t _binary_texture_strawberry_strawberry_data_start __asm("_binary_texture_strawberry_strawberry_data_start");
extern uint32_t _binary_texture_strawberry_strawberry_data_end __asm("_binary_texture_strawberry_strawberry_data_end");
extern uint32_t _binary_texture_strawberry_strawberry_data_size __asm("_binary_texture_strawberry_strawberry_data_size");
