{
  .start = (void *)0,
  .size = (uint32_t)0,
  .offset = 0,
  .width = 0,
  .height = 0,
  .v_mul = 0, // 0
},
{
  .start = (void *)&_binary_bsp_katdm3_textures_katdm3_kt_rivit_strap2_cont_dk_data_start,
  .size = (uint32_t)&_binary_bsp_katdm3_textures_katdm3_kt_rivit_strap2_cont_dk_data_size,
  .offset = 0,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)&_binary_bsp_baseq3_textures_gothic_trim_metalsupport4small_data_start,
  .size = (uint32_t)&_binary_bsp_baseq3_textures_gothic_trim_metalsupport4small_data_size,
  .offset = 174768,
  .width = 64,
  .height = 64,
  .v_mul = 1.0, // 64
},
{
  .start = (void *)0,
  .size = (uint32_t)0,
  .offset = 185696,
  .width = 0,
  .height = 0,
  .v_mul = 0, // 0
},
{
  .start = (void *)0,
  .size = (uint32_t)0,
  .offset = 185696,
  .width = 0,
  .height = 0,
  .v_mul = 0, // 0
},
{
  .start = (void *)0,
  .size = (uint32_t)0,
  .offset = 185696,
  .width = 0,
  .height = 0,
  .v_mul = 0, // 0
},
{
  .start = (void *)&_binary_bsp_katdm3_textures_katdm3_kt_rock_1f_shiny_dk_data_start,
  .size = (uint32_t)&_binary_bsp_katdm3_textures_katdm3_kt_rock_1f_shiny_dk_data_size,
  .offset = 185696,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)0,
  .size = (uint32_t)0,
  .offset = 360464,
  .width = 0,
  .height = 0,
  .v_mul = 0, // 0
},
{
  .start = (void *)0,
  .size = (uint32_t)0,
  .offset = 360464,
  .width = 0,
  .height = 0,
  .v_mul = 0, // 0
},
{
  .start = (void *)0,
  .size = (uint32_t)0,
  .offset = 360464,
  .width = 0,
  .height = 0,
  .v_mul = 0, // 0
},
{
  .start = (void *)0,
  .size = (uint32_t)0,
  .offset = 360464,
  .width = 0,
  .height = 0,
  .v_mul = 0, // 0
},
{
  .start = (void *)&_binary_bsp_baseq3_textures_gothic_floor_largerblock3b3x128_data_start,
  .size = (uint32_t)&_binary_bsp_baseq3_textures_gothic_floor_largerblock3b3x128_data_size,
  .offset = 360464,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)0,
  .size = (uint32_t)0,
  .offset = 535232,
  .width = 0,
  .height = 0,
  .v_mul = 0, // 0
},
{
  .start = (void *)&_binary_bsp_katdm3_textures_katdm3_kt_rock_1f_rot_fade_data_start,
  .size = (uint32_t)&_binary_bsp_katdm3_textures_katdm3_kt_rock_1f_rot_fade_data_size,
  .offset = 535232,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)&_binary_bsp_baseq3_textures_gothic_trim_km_arena1tower4_a_data_start,
  .size = (uint32_t)&_binary_bsp_baseq3_textures_gothic_trim_km_arena1tower4_a_data_size,
  .offset = 710000,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)&_binary_bsp_katdm3_textures_katdm3_kattex_3_stone_bmp_data_start,
  .size = (uint32_t)&_binary_bsp_katdm3_textures_katdm3_kattex_3_stone_bmp_data_size,
  .offset = 884768,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)&_binary_bsp_baseq3_textures_gothic_block_smblk3b3dim_wall_data_start,
  .size = (uint32_t)&_binary_bsp_baseq3_textures_gothic_block_smblk3b3dim_wall_data_size,
  .offset = 1059536,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)&_binary_bsp_baseq3_textures_gothic_trim_border2_data_start,
  .size = (uint32_t)&_binary_bsp_baseq3_textures_gothic_trim_border2_data_size,
  .offset = 1234304,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)&_binary_bsp_baseq3_textures_gothic_wall_streetbricks10_data_start,
  .size = (uint32_t)&_binary_bsp_baseq3_textures_gothic_wall_streetbricks10_data_size,
  .offset = 1409072,
  .width = 128,
  .height = 128,
  .v_mul = 1.0, // 128
},
{
  .start = (void *)&_binary_bsp_baseq3_textures_gothic_block_blocks18b_data_start,
  .size = (uint32_t)&_binary_bsp_baseq3_textures_gothic_block_blocks18b_data_size,
  .offset = 1452768,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)&_binary_bsp_baseq3_textures_gothic_trim_metalsupsolid_data_start,
  .size = (uint32_t)&_binary_bsp_baseq3_textures_gothic_trim_metalsupsolid_data_size,
  .offset = 1627536,
  .width = 128,
  .height = 128,
  .v_mul = 1.0, // 128
},
{
  .start = (void *)&_binary_bsp_baseq3_textures_gothic_trim_km_arena1tower4_data_start,
  .size = (uint32_t)&_binary_bsp_baseq3_textures_gothic_trim_km_arena1tower4_data_size,
  .offset = 1671232,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)&_binary_bsp_baseq3_textures_gothic_trim_supportborder_data_start,
  .size = (uint32_t)&_binary_bsp_baseq3_textures_gothic_trim_supportborder_data_size,
  .offset = 1846000,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)&_binary_bsp_baseq3_textures_gothic_trim_tower_top_data_start,
  .size = (uint32_t)&_binary_bsp_baseq3_textures_gothic_trim_tower_top_data_size,
  .offset = 2020768,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)&_binary_bsp_katdm3_textures_katdm3_kt_rock_1f_rot_shiny_data_start,
  .size = (uint32_t)&_binary_bsp_katdm3_textures_katdm3_kt_rock_1f_rot_shiny_data_size,
  .offset = 2195536,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)0,
  .size = (uint32_t)0,
  .offset = 2370304,
  .width = 0,
  .height = 0,
  .v_mul = 0, // 0
},
{
  .start = (void *)0,
  .size = (uint32_t)0,
  .offset = 2370304,
  .width = 0,
  .height = 0,
  .v_mul = 0, // 0
},
{
  .start = (void *)&_binary_bsp_katdm3_textures_katdm3_kattex_3_stone_bmp_rot_data_start,
  .size = (uint32_t)&_binary_bsp_katdm3_textures_katdm3_kattex_3_stone_bmp_rot_data_size,
  .offset = 2370304,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)0,
  .size = (uint32_t)0,
  .offset = 2545072,
  .width = 0,
  .height = 0,
  .v_mul = 0, // 0
},
{
  .start = (void *)&_binary_bsp_katdm3_textures_katdm3_kattex_3_stone_bmp_fade_data_start,
  .size = (uint32_t)&_binary_bsp_katdm3_textures_katdm3_kattex_3_stone_bmp_fade_data_size,
  .offset = 2545072,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)&_binary_bsp_katdm3_textures_katdm3_kt_wood_rough_data_start,
  .size = (uint32_t)&_binary_bsp_katdm3_textures_katdm3_kt_wood_rough_data_size,
  .offset = 2719840,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)&_binary_bsp_katdm3_models_mapobjects_kt_torch_kt_torch_data_start,
  .size = (uint32_t)&_binary_bsp_katdm3_models_mapobjects_kt_torch_kt_torch_data_size,
  .offset = 2894608,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)&_binary_bsp_baseq3_textures_sfx_flame1_data_start,
  .size = (uint32_t)&_binary_bsp_baseq3_textures_sfx_flame1_data_size,
  .offset = 3069376,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)0,
  .size = (uint32_t)0,
  .offset = 3244144,
  .width = 0,
  .height = 0,
  .v_mul = 0, // 0
},
{
  .start = (void *)&_binary_bsp_katdm3_models_mapobjects_oak_oakblaetter_data_start,
  .size = (uint32_t)&_binary_bsp_katdm3_models_mapobjects_oak_oakblaetter_data_size,
  .offset = 3244144,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
{
  .start = (void *)&_binary_bsp_baseq3_models_mapobjects_skel_skel_data_start,
  .size = (uint32_t)&_binary_bsp_baseq3_models_mapobjects_skel_skel_data_size,
  .offset = 3418912,
  .width = 256,
  .height = 256,
  .v_mul = 1.0, // 256
},
