#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

extern uint32_t _binary_bsp_baseq3_textures_gothic_trim_km_arena1tower4_a_data_start __asm("_binary_bsp_baseq3_textures_gothic_trim_km_arena1tower4_a_data_start");
extern uint32_t _binary_bsp_baseq3_textures_gothic_trim_km_arena1tower4_a_data_end __asm("_binary_bsp_baseq3_textures_gothic_trim_km_arena1tower4_a_data_end");
extern uint32_t _binary_bsp_baseq3_textures_gothic_trim_km_arena1tower4_a_data_size __asm("_binary_bsp_baseq3_textures_gothic_trim_km_arena1tower4_a_data_size");

#ifdef __cplusplus
}
#endif
