#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

extern uint32_t _binary_bsp_baseq3_textures_gothic_floor_largerblock3b3x128_data_start __asm("_binary_bsp_baseq3_textures_gothic_floor_largerblock3b3x128_data_start");
extern uint32_t _binary_bsp_baseq3_textures_gothic_floor_largerblock3b3x128_data_end __asm("_binary_bsp_baseq3_textures_gothic_floor_largerblock3b3x128_data_end");
extern uint32_t _binary_bsp_baseq3_textures_gothic_floor_largerblock3b3x128_data_size __asm("_binary_bsp_baseq3_textures_gothic_floor_largerblock3b3x128_data_size");

#ifdef __cplusplus
}
#endif
